distribution:
  name: webships
  title: Webships
  webroot: web
  profile_repo: webships/webships
  project_template: webships/webships-project
users:
  - authenticated
  - app_admin
  - api_admin
  - administrator
user:
  authenticated:
    name: Authenticated user
    mail: test.authenticated@webship.org
    password: dD.123123ddd
    role: _none_
  app_admin:
    name: App Admin
    mail: test.app_admin@webship.org
    password: dD.123123ddd
    role: api_admin
  api_admin:
    name: API Admin
    mail: test.api_admin@webship.org
    password: dD.123123ddd
    role: api_admin
  administrator:
    name: Super Admin
    mail: test.administrator@webship.org
    password: dD.123123ddd
    role: administrator
