products:
  -
    name: 'uber_publisher-project'
    git_drupal: ''
    git_github: 'git@github.com:Vardot/uber_publisher-project.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher'
    git_drupal: 'git@git.drupal.org:project/uber_publisher.git'
    git_github: 'git@github.com:Vardot/uber_publisher.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_core'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_core.git'
    git_github: 'git@github.com:Vardot/uber_publisher_core.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_opinion_articles'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_opinion_articles.git'
    git_github: 'git@github.com:Vardot/uber_publisher_opinion_articles.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_author_profile'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_author_profile.git'
    git_github: 'git@github.com:Vardot/uber_publisher_author_profile.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_breaking_news'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_breaking_news.git'
    git_github: 'git@github.com:Vardot/uber_publisher_breaking_news.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_daily_cartoons'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_daily_cartoons.git'
    git_github: 'git@github.com:Vardot/uber_publisher_daily_cartoons.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_in_pictures'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_in_pictures.git'
    git_github: 'git@github.com:Vardot/uber_publisher_in_pictures.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_search'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_search.git'
    git_github: 'git@github.com:Vardot/uber_publisher_search.git'
    branch: '8.x-4.x'
  -
    name: 'uber_publisher_social_post'
    git_drupal: 'git@git.drupal.org:project/uber_publisher_social_post.git'
    git_github: 'git@github.com:Vardot/uber_publisher_social_post.git'
    branch: '8.x-4.x'
    
    
    
    