doc:
  name: themes
  path: /var/www/html/themes
web:
  url: http://localhost/themes
database:
  prefix: themes_
vdo_drupal:
  template_drupal_theme_name: template_drupal
themes:
  - flexi_pattern_lab
  - zilch
  - abeesparadise
  - abovolab
  - adaptivetheme
  - aegan
  - material
  - agov_base
  - agov_nsw
  - agov_whitlam
  - amazeui
  - amptheme
  - architect
  - arriaga
  - awesome
  - awesome_zymphonies_theme
  - badcamp_sight
  - bank_zymphonies_theme
  - barnettechetjlb
  - bootstrap_barrio
  - base_zymphonies_theme
  - basic
  - bassline
  - bealestreet
  - bear_skin
  - beauty_salon_zymphonies_theme
  - beep_edition
  - beginning
  - belgrade
  - belle
  - bem
  - beryllium
  - blocky
  - blogz
  - blueadmino
  - bluemarine
  - bluemasters
  - bones_theme
  - bon_voyage
  - bootbase
  - bootstrap
  - bootstrap_sass
  - bootstrapblog
  - bootstrap_business
  - bootstrap_clean_blog
  - bootstrap_forms
  - bootstrap_light
  - bootstrap_lite
  - bootstrap_mint
  - bootstrap_pointnet
  - rainbow
  - bootstrap_rijkshuisstijl
  - bootstrap_subtheme_rtl
  - bootstrap4
  - bootstrapper
  - bourbon
  - boxes_uikitty
  - breeze
  - bridge
  - bs_base
  - bt_theme
  - bulma
  - business
  - businessgroup_zymphonies_theme
  - business_listing_zymphonies_theme
  - business_responsive_theme
  - businessplus_lite
  - busy
  - byu_amp_theme
  - byu_theme
  - camaleon
  - car_zymphonies_theme
  - casper
  - champs_base
  - charity_zymphonies_theme
  - cherryblossom
  - civi_bartik
  - claro
  - classa11y
  - d8_blog_theme
  - clean_blog
  - clinic_zymphonies_theme
  - cloud_zymphonies_theme
  - cog
  - colonel
  - coloradmin
  - commerce_bootstrap
  - uikitty_components
  - concedra_theme
  - conference_lite
  - contacts_theme
  - corolla
  - corporate_corp_theme
  - corporate_lite
  - corporate_blue
  - corporation
  - creative_theme
  - creative_responsive_theme
  - stem_theme
  - creativity
  - credit_due
  - da_vinci
  - danland
  - dawn
  - designer
  - devblog
  - dg_theme
  - diba_core
  - dopetrope
  - drulma
  - drumob
  - drupal8_custom_theme
  - drupal8_parallax_theme
  - premier_league
  - drupal_light
  - d8w3css
  - drupal8_zymphonies_theme
  - drupalcoders_bootstrap
  - drupalexp_lite
  - druppio_monopage
  - druppio_small_business
  - easy_news
  - ebiz
  - ebook_zymphonies_theme
  - edynamic_theme
  - eight
  - electra
  - eleven
  - ember
  - empty_theme
  - emulsify
  - estore
  - everest
  - exsen
  - fepper
  - flame
  - flexi
  - flexible
  - flow2
  - fontfolio
  - form3
  - fortytwo
  - foundation_patterns
  - foundation6
  - fusion
  - garland
  - gesso
  - glisseo
  - gogland
  - gordon
  - govuk_design_system
  - govcms8_uikit_starter
  - govcms8_ui
  - gratis
  - great_zymphonies_theme
  - green_theme
  - guesthouse_lite
  - guru
  - helios_responsive
  - himalaya
  - holy
  - hwc
  - hops
  - hotbed
  - icemagic
  - ideastorm
  - iu
  - industrial_zymphonies_theme
  - insha
  - integrity
  - intercept_base
  - isosceles_theme
  - janitor
  - jethro
  - jouve_seven
  - kalatheme
  - kanji
  - kashmir
  - kaziranga
  - khan
  - lab
  - landingpage_zymphonies_theme
  - law_firm_theme
  - liberty
  - light_skeleton
  - light_zymphonies_theme
  - likable
  - litejazz
  - louie
  - magazine_lite
  - management
  - marinelli
  - matter
  - material_base
  - material_corporate
  - mdc
  - materialize
  - mayo
  - mbase
  - medicare_zymphonies_theme
  - mediteran
  - medium_theme
  - mediumish_blog
  - menuistic
  - mili
  - milligram
  - minima
  - minimal
  - mdb
  - minimal_lite
  - minimax
  - mobidic
  - mobile
  - mobileapp_zymphonies_theme
  - mono
  - moonwalk
  - mulpo
  - multipurpose_corporate_theme
  - musicians
  - mytheme
  - neato
  - nebula
  - nebula_demo
  - nebula_example
  - neon
  - nero
  - news_zymphonies_theme
  - newsflash
  - newsplus_lite
  - nexus
  - nightar
  - nigraphic
  - ninesixty
  - nitty
  - nittygritty
  - addweb_drupal_back_end_theme
  - noor
  - octavia
  - black_old
  - om
  - ombak
  - omega
  - onepage_zymphonies_theme
  - onescreen
  - openchurch_theme
  - os_base
  - paper
  - paraboot
  - paragon_adminkit
  - paragon_themekit
  - particle_responsive
  - patternlab
  - paxton
  - blog_theme
  - pets_zymphonies_theme
  - photo
  - photographer
  - pistachio
  - pixels
  - pixture_reloaded
  - platinum
  - platon
  - portfolio_theme
  - pragtic
  - prius
  - proboci
  - professional_responsive_theme
  - professional_theme
  - property_zymphonies_theme
  - prototype
  - qatar_zymphonies_theme
  - qatar2022_zymphonies_theme
  - quickseed_theme
  - quickseed2017gci
  - quickseedgci
  - quickseed
  - radix
  - reactify
  - red
  - release_branch
  - restaurant_lite
  - restaurant_zymphonies_theme
  - robotic
  - root
  - sailor
  - sales_zymphonies_theme
  - samara
  - school_zymphonies_theme
  - searchify
  - semantica
  - sensible
  - seventeen
  - shakespeare
  - shiv
  - shop_item
  - showcase_lite
  - classic_corporate_theme
  - simpleblog
  - simply
  - skeletontheme
  - sketch
  - smallbusiness
  - solid
  - space
  - spacelift
  - spatial_theme
  - spectre
  - spring_bloom
  - sshop
  - stagb
  - starlight
  - startupgrowth_lite
  - startup_zymphonies_theme
  - store_zymphonies_theme
  - tailwindcss
  - tao
  - tapestry
  - tara
  - teacher
  - teacosy
  - teatheme
  - teka
  - theone
  - themage
  - titus
  - topplus_lite
  - torsion
  - travel_zymphonies_theme
  - treetop
  - triculin_responsive
  - tweme
  - twentyseventeen
  - twentyfifteen
  - uswds
  - uikit
  - uikitapi
  - uikit_blog
  - uikitty
  - uikitty3
  - uikitty_starter
  - umami
  - used_cars
  - uswds_base
  - vartheme
  - vartheme_bs4
  - vartheme_material
  - ven
  - verti
  - visually_impaired_theme
  - void
  - waterloo
  - wet4
  - wxt_bootstrap
  - webpackrs
  - webtheme
  - whitecanvas
  - whitejazz
  - windup
  - wonder_zymphonies_theme
  - writer
  - xbase
  - xseven
  - xtheme
  - yeti_theme
  - yg_aesthetic
  - yg_agency
  - yg_app
  - yg_app_one
  - yg_architect
  - yg_asymmetry
  - yg_biz
  - yg_black
  - yg_bold
  - yg_booster
  - yg_business
  - yg_business_line
  - yg_business_one
  - yg_business_plus
  - yg_car_care
  - yg_charity
  - yg_concept
  - yg_construction
  - yg_construction_lite
  - yg_corp
  - yg_corporate
  - yg_corporate_lite
  - yg_creative
  - yg_dentalcare
  - yg_elate
  - yg_event_organizer
  - yg_fitness_center
  - yg_fitness_gym
  - yg_flew
  - yg_flexy
  - yg_freelancer
  - yg_glow
  - yg_greatness
  - yg_hotel
  - yg_iconic
  - yg_insurance
  - yg_intechnic
  - yg_interior
  - yg_justice
  - yg_launcher
  - yg_law
  - yg_law_firm
  - yg_learn
  - yg_logistics
  - yg_magazine
  - yg_medical
  - yg_medicare
  - yg_multipurpose
  - yg_music
  - yg_newage
  - yg_news
  - yg_orange
  - yg_photography
  - yg_pixel
  - yg_plumbing
  - yg_profile
  - yg_property_one
  - yg_relic
  - yg_restaurant
  - yg_restaurant_lite
  - yg_simple
  - yg_solid
  - yg_sports
  - yg_sprint
  - yg_verb
  - zen
  - zippy
  - zircon
  - ztheme
  - zurb_clean_blog
  - zurb_foundation
  - zurb_template
admin_themes:
  - adminimal_theme
  - material_admin
  - vartheme_admin
  - vartheme_material_admin
  - thunder_admin
  - druadmin_lte_theme
  - agnian_material_admin
  - claro
  - material_base
  - eleven
  - admintheme
  - uikit_admin
  - true_admin
  - smart_admin_theme
  - smarty_admin
  - bootstrap_admin
  - bt_admin_theme
  - simple_admin
  - hostinstantlyadmintheme
  - endless_admin
  - fortytwo_admin
  - om_admin
  - seaside_admin